// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rycrumkxqftiolzfyxdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5Y3J1bWt4cWZ0aW9semZ5eGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzczOTgsImV4cCI6MjA2OTgxMzM5OH0.4lq_tU2cAAnqyn6VKDSBSgSTeCat-hiQwd8PcYSDQ8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});